# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-01 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default=b'An Awesome Person', help_text=b'Resume Title', max_length=255)),
                ('intro', models.TextField(help_text=b'Long-form intro text visible on resume')),
                ('description', models.TextField(help_text=b'Meta description or notes not visible on resume')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeItemLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume')),
            ],
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='description',
            field=models.TextField(blank=True, max_length=2047),
        ),
        migrations.AddField(
            model_name='resumeitemlink',
            name='resumeitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.ResumeItem'),
        ),
    ]
